apiVersion: apps/v1
kind: Deployment
metadata:
  name: golang-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: golang-app
  template:
    metadata:
      labels:
        app: golang-app
    spec:
      containers:
      - name: golang-container
        image: yourdockerhubusername/golang-app:latest
        ports:
        - containerPort: 8080
