# k8s/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: golang-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: golang-app
  template:
    metadata:
      labels:
        app: golang-app
    spec:
      containers:
      - name: golang-container
        # --- CHANGE 3: Update image name with your Docker Hub username ---
        image: tejas20012001/golang-app:latest
        ports:
        - containerPort: 8080